CREATE DATABASE customer_behavior;
USE customer_behavior;
SELECT * FROM customer limit 5;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT *
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount) FROM customer
);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT Item_Purchased,
       AVG(review_rating) AS avg_review_rating
FROM customer
GROUP BY Item_Purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,
       AVG(purchase_amount) AS avg_purchase
FROM customer
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 

SELECT subscription_status,
       AVG(purchase_amount) AS avg_spend
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT subscription_status,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 

SELECT customer_id,
       SUM(previous_purchases) AS total_purchases,
       CASE 
           WHEN SUM(previous_purchases) = 0 THEN 'New'
           WHEN SUM(previous_purchases) BETWEEN 1 AND 5 THEN 'Returning'
           ELSE 'Loyal'
       END AS customer_segment
FROM customer
GROUP BY customer_id;

-- Q8. What are the top 3 most purchased products within each category? 

SELECT *
FROM (
    SELECT category,
           Item_Purchased,
           COUNT(*) AS total_orders,
           RANK() OVER (PARTITION BY category 
                        ORDER BY COUNT(*) DESC) AS rnk
    FROM customer
    GROUP BY category, Item_Purchased
) ranked
WHERE rnk <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(*) AS total_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 

SELECT 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        ELSE '46+'
    END AS age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        ELSE '46+'
    END
ORDER BY total_revenue DESC;